### ISSUE TITLE
Hi! I failed the test on win10

### ISSUE THREAD

**Issue by XTeam-Wing** [pkb1s/SharpRelay#1]
C:\Users\Ninja\Desktop\360\Github\SharpRelay\SharpRelay\bin>SharpRelay.exe fakeservice WinDivert64.sys 445 8445
[+] Checking if service already exists...
[+] Service not found! Creating new service to load driver...
[!] Service could not be created!

**Comment by pkb1s** [comment]
Hi,

Are you running it with local admin rights? SharpRelay is trying to create a new service to load the driver and needs elevated permissions. 

Also the service name needs to be unique so if you run it again make sure you pick another name or remove any previous services you created with the tool.

**Comment by pkb1s** [comment]
Also, try running it with the path to .sys in quotes like the following

`SharpRelay.exe testservice "C:\Users\user\Desktop\SharpRelay\SharpRelay\bin\intercept.sys" 445 8445`

You need to unload the driver or reboot before you try again.

**Comment by XTeam-Wing** [comment]
wow!Thanks!!!
